### ISSUE TITLE
dl_image_jpeg.cpp fails to compile with IDF 6.0.0, flags and pixel_reverse members do not exist

### ISSUE THREAD

**Issue by shengt25** [espressif/esp-dl#299]
### Checklist

- [x] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [x] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [x] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

dl_image_jpeg.cpp should compile successfully with ESP-IDF 6.0.0.

### Actual behavior (suspected bug)

Build fails with three compilation errors:
```
error: 'jpeg_decode_engine_cfg_t' has no non-static data member named 'flags'
error: 'jpeg_encode_engine_cfg_t' has no non-static data member named 'flags'                                                                                                                                                                                                                                           
error: 'jpeg_encode_cfg_t' has no non-static data member named 'pixel_reverse'
```

### Error logs or terminal output

```shell
[]/managed_components/espressif__esp-dl/vision/image/dl_image_jpeg.cpp:242:5: error: 'jpeg_decode_engine_cfg_t' has no non-static data member named 'flags'
  242 |     };
      |     ^
[]/managed_components/espressif__esp-dl/vision/image/dl_image_jpeg.cpp: In function 'dl::image::jpeg_img_t dl::image::hw_encode_jpeg_base(const img_t&, uint8_t, int, jpeg_down_sampling_type_t)':
[]/managed_components/espressif__esp-dl/vision/image/dl_image_jpeg.cpp:315:5: error: 'jpeg_encode_engine_cfg_t' has no non-static data member named 'flags'
  315 |     };
      |     ^
[]/managed_components/espressif__esp-dl/vision/image/dl_image_jpeg.cpp:349:5: error: 'jpeg_encode_cfg_t' has no non-static data member named 'pixel_reverse'
  349 |     };
      |     ^
[10/317] Building CXX object esp-idf/espressif__esp-dl/CMakeFiles/__idf_espressif__esp-dl.dir/vision/image/dl_image_pixel_cvt_dispatch_yuv2rgb888.cpp.obj
```

### Steps to reproduce the behavior

1. Create a project targeting ESP32-P4 with ESP-IDF v6.0.0
2. Add esp-dl as a managed component (commit 3401d90)
3. Call any function that triggers JPEG hardware encode/decode, e.g.:
```
  #include "dl_image_jpeg.hpp"                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                          
  dl::image::hw_decode_jpeg(jpeg_img, DL_IMAGE_PIX_TYPE_RGB888, 3000);                                                                                                                                                                                                                                                    
  // or           
  dl::image::hw_encode_jpeg(img, 90); 
```                                                                                                                                                                                                                                                                                    
 
4. Run idf.py build                       

### Project release version

v3.3.2

### System architecture

ARM 64-bit (Apple M1/M2, Raspberry Pi 4/5)

### Operating system

MacOS

### Operating system version

26.4

### Shell

ZSH

### Additional context

Workaround: 

In `managed_components/espressif__esp-dl/vision/image/dl_image_jpeg.cpp`, remove the three conditional blocks:                                                                                                                                                                                                                             
   
  #if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(6, 0, 0)
      .flags = {0},                                                                                                                                                                                                                                                                                                       
  #endif
                                                                                                                                                                                                                                                                                                                          
  #if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(6, 0, 0)                                                                                                                                                                                                                                                                     
      .flags = {0},
  #endif                                                                                                                                                                                                                                                                                                                  
                  
  #if ESP_IDF_VERSION >= ESP_IDF_VERSION_VAL(6, 0, 0)
      .pixel_reverse = false,
  #endif

**Comment by BlueSkyB** [comment]
This requires updating to **ESP-IDF 6.0** — these members were added in the latest release 6.0, and slightly older ESP-IDF 6.0 releases indeed do not have them.

Also, if you encounter **`no_return`** or **OpenCV linking errors** when compiling with ESP-IDF 6.0, it's because version 6.0 enables **picolibc** by default, replacing the previous **newlib**. Quick workaround: **disable picolibc in your project**.

**Comment by shengt25** [comment]
> This requires updating to **ESP-IDF 6.0** — these members were added in the latest release 6.0, and slightly older ESP-IDF 6.0 releases indeed do not have them.
> 
> Also, if you encounter **`no_return`** or **OpenCV linking errors** when compiling with ESP-IDF 6.0, it's because version 6.0 enables **picolibc** by default, replacing the previous **newlib**. Quick workaround: **disable picolibc in your project**.

Thanks for the clarification! Yes I could confirm that this is fixed in the latest release/v6.0 branch.

The issue was I'm using eim to manage the environment now. By default eim installs tag v6.0, which is slightly older than release/v6.0. (ESP-IDF v6.0 tag and release/v6.0 are different.)

To update, reinstall via `eim install` with argument `--idf-versions release-v6.0`, or use the `eim wizard` and choose 'release-v6.0'.
