### ISSUE TITLE
Compilation error with ESP-IDF v6.0: need to update esp-dsp to v1.8 and update mbedtls AES API

### ISSUE THREAD

**Issue by shengt25** [espressif/esp-dl#295]
### Checklist

- [x] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [x] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [x] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

After upgrading from ESP-IDF v5.5.1 to v6.0, the project with ESP-DL should compile successfully.

### Actual behavior (suspected bug)

It fails to compile, with esp-dsp v1.7 component. It gives errors stating that standard math functions like atan and cos are not found in the std namespace in the file ekf_imu13states.cpp.

I've checked the esp-dsp repo, in commit https://github.com/espressif/esp-dsp/commit/23ee959982b90a1a920b2198b7e380797f39fee1 this issue has been fixed. The depencencies in ESP-DL should update to v1.8.

The mbedtls AES API also needs update with IDF v6.0

### Error logs or terminal output

```shell
[...]/managed_components/espressif__esp-dsp/modules/kalman/ekf_imu13states/ekf_imu13states.cpp: In member function 'void ekf_imu13states::TestFull(bool)':
[...]/managed_components/espressif__esp-dsp/modules/kalman/ekf_imu13states/ekf_imu13states.cpp:121:21: error: 'atan' is not a member of 'std'; did you mean 'atan'?
  121 |     float pi = std::atan(1) * 4;
      |                     ^~~~
In file included from [...]/esp-15.2.0_20251204/riscv32-esp-elf/picolibc/include/math.h:114:15: note: 'atan' declared here
  114 | extern double atan (double);
      |               ^~~~

[...]/managed_components/espressif__esp-dsp/modules/kalman/ekf_imu13states/ekf_imu13states.cpp:154:45: error: 'cos' is not a member of 'std'; did you mean 'ios'?
  154 |             gyro_data(0, 0) = 1 / pi * std::cos(-pi / 2 + pi / 2 * count * 2 / (total_N / 10));
      |                                             ^~~
      |                                             ios
[...]/managed_components/espressif__esp-dsp/modules/kalman/ekf_imu13states/ekf_imu13states.cpp:155:45: error: 'cos' is not a member of 'std'; did you mean 'ios'?
  155 |             gyro_data(1, 0) = 2 / pi * std::cos(-pi / 2 + pi / 2 * count * 2 / (total_N / 10));
      |                                             ^~~
      |                                             ios
```

Similiar error also happens in `managed_components/espressif__esp-dsp/modules/kalman/ekf/common/ekf.cpp:253:21`

Error in `mbedtls/aes.h`:
```
managed_components/espressif__esp-dl/fbs_loader/src/fbs_loader.cpp:2:10: fatal error: mbedtls/aes.h: No such file or directory
    2 | #include "mbedtls/aes.h"
      |          ^~~~~~~~~~~~~~~
compilation terminated.
[25/359] Building CXX object esp-idf/espressif__esp-dl/CMakeFiles/__idf_espressif__esp-dl.dir/dl/model/src/dl_model_base.cpp.obj
ninja: build stopped: subcommand failed.
Missing "mbedtls/aes.h" file name found in the following component(s): openthread([...]/components/openthread/openthread/third_party/mbedtls/repo/include/mbedtls/aes.h). Maybe one of the components needs to add the missing header directory to INCLUDE_DIRS of idf_component_register call in CMakeLists.txt. Another possibility may be that the component or its feature is not enabled in the configuration. Use "idf.py menuconfig" to check if the required options are enabled.
```

### Steps to reproduce the behavior

Target Chip: ESP32-P4
Toolchain: riscv32-esp-elf-gcc (esp-15.2.0_20251204)
Build System: Ninja / CMake

Set up an environment with ESP-IDF v6.0.
Include the esp-dl component in the project.
Attempt to compile the project.

### Project release version

v3.3.0

### System architecture

ARM 64-bit (Apple M1/M2, Raspberry Pi 4/5)

### Operating system

MacOS

### Operating system version

26.4

### Shell

ZSH

**Comment by BlueSkyB** [comment]
Thank you for your code contribution. Your PR has been merged. Please update ESP-DL and try again.
